"""Render the canonical QMD manuscript into the anonymous INFORMS TeX file."""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "paper" / "CRPTO_ijds.qmd"
TEMPLATE = ROOT / "paper" / "submission" / "informs-pandoc-template.tex"
OUTPUT = ROOT / "paper" / "submission" / "CRPTO_ijds_submission.tex"

GENERATED_BANNER = """%% =====================================================================
%% GENERATED FROM paper/CRPTO_ijds.qmd. DO NOT EDIT THIS FILE DIRECTLY.
%% Build: uv run python scripts/build_ijds_submission_tex.py
%% Compile: latexmk -pdf -gg -interaction=nonstopmode CRPTO_ijds_submission.tex
%% Windows fallback: pdflatex, bibtex, pdflatex, pdflatex.
%% =====================================================================
"""


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def render_submission_tex(*, check: bool = False) -> bool:
    """Render the source and return whether the checked output was current."""
    with tempfile.TemporaryDirectory(prefix=".crpto-ijds-", dir=SOURCE.parent) as temporary:
        rendered = Path(temporary) / SOURCE.with_suffix(".tex").name
        command = [
            "quarto",
            "render",
            str(SOURCE),
            "--to",
            "latex",
            "--metadata",
            "cite-method:natbib",
            "--template",
            str(TEMPLATE),
            "--output-dir",
            rendered.parent.name,
        ]
        subprocess.run(command, cwd=ROOT, check=True)
        body = rendered.read_text(encoding="utf-8")

    # The source is one directory above the official output. Quarto preserves
    # source-relative image paths, so adjust them deterministically for TeX.
    body = body.replace("{../reports/", "{../../reports/")
    payload = (GENERATED_BANNER + body).encode("utf-8")

    if check:
        if not OUTPUT.exists():
            return False
        return _sha256(OUTPUT.read_bytes()) == _sha256(payload)

    OUTPUT.write_bytes(payload)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the official TeX differs from the generated manuscript",
    )
    args = parser.parse_args()
    current = render_submission_tex(check=args.check)
    if args.check and not current:
        print(f"stale generated manuscript: {OUTPUT.relative_to(ROOT)}")
        return 1
    print(
        f"submission TeX {'is current' if args.check else 'rendered'}: {OUTPUT.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
