"""Build deterministic active and reserve views of the IJDS master bibliography."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path

from src.utils.pipeline_runtime import atomic_write_text

ROOT = Path(__file__).resolve().parents[1]
MASTER_RELATIVE = Path("paper/references.bib")
SOURCE_RELATIVES = (Path("paper/CRPTO_ijds.qmd"), Path("paper/supplement_ijds.qmd"))
ACTIVE_RELATIVE = Path("paper/references_active.bib")
RESERVE_RELATIVE = Path("paper/references_reserve.bib")
PARTITION_RELATIVE = Path("paper/references_partition.json")

ENTRY_START = re.compile(r"(?m)^[ \t]*@(?P<kind>[A-Za-z]+)[ \t]*(?P<opening>[({])")
ENTRY_KEY = re.compile(
    r"^\s*@[A-Za-z]+\s*[({]\s*(?P<key>[^,\s]+)\s*,",
    flags=re.DOTALL,
)
CITATION = re.compile(r"(?<![\w@])-?@(?P<key>[A-Za-z][A-Za-z0-9_:-]*)")
HTML_COMMENT = re.compile(r"<!--.*?-->", flags=re.DOTALL)
INLINE_CODE = re.compile(r"`+[^`\n]*`+")
CROSS_REFERENCE_PREFIXES = (
    "cau-",
    "cnj-",
    "cor-",
    "def-",
    "eq-",
    "exm-",
    "exr-",
    "fig-",
    "imp-",
    "lem-",
    "lst-",
    "nte-",
    "prp-",
    "sec-",
    "tbl-",
    "thm-",
    "tip-",
    "wrn-",
)
SPECIAL_ENTRY_TYPES = {"comment", "preamble", "string"}


@dataclass(frozen=True)
class BibEntry:
    """One keyed BibTeX entry, retaining its exact master text."""

    kind: str
    key: str
    text: str


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def parse_bibtex_entries(text: str) -> tuple[BibEntry, ...]:
    """Parse complete top-level entries without normalizing their field contents."""
    entries: list[BibEntry] = []
    seen_casefolded: dict[str, str] = {}
    position = 0
    while match := ENTRY_START.search(text, position):
        kind = match.group("kind")
        if kind.casefold() in SPECIAL_ENTRY_TYPES:
            raise RuntimeError(
                f"Unkeyed BibTeX directive @{kind} is unsupported by the partition contract."
            )
        opening = match.group("opening")
        closing = "}" if opening == "{" else ")"
        depth = 1
        escaped = False
        cursor = match.end()
        while cursor < len(text) and depth:
            character = text[cursor]
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == opening:
                depth += 1
            elif character == closing:
                depth -= 1
            cursor += 1
        if depth:
            raise RuntimeError(f"Unterminated BibTeX entry beginning at byte {match.start()}.")

        entry_text = text[match.start() : cursor].strip()
        key_match = ENTRY_KEY.match(entry_text)
        if key_match is None:
            raise RuntimeError(f"BibTeX entry @{kind} has no parseable key.")
        key = key_match.group("key")
        folded = key.casefold()
        if folded in seen_casefolded:
            prior = seen_casefolded[folded]
            raise RuntimeError(f"Duplicate BibTeX keys under case-folding: {prior!r} and {key!r}.")
        seen_casefolded[folded] = key
        entries.append(BibEntry(kind=kind, key=key, text=entry_text))
        position = cursor

    if not entries:
        raise RuntimeError("The master bibliography contains no keyed BibTeX entries.")
    return tuple(entries)


def _without_nonrendered_markdown(text: str) -> str:
    """Remove comments and code spans that Pandoc does not treat as citations."""
    uncommented = HTML_COMMENT.sub("", text)
    visible: list[str] = []
    fence_character: str | None = None
    fence_length = 0
    for line in uncommented.splitlines():
        fence_match = re.match(r"^\s*(`{3,}|~{3,})", line)
        if fence_match is not None:
            marker = fence_match.group(1)
            if fence_character is None:
                fence_character = marker[0]
                fence_length = len(marker)
            elif marker[0] == fence_character and len(marker) >= fence_length:
                fence_character = None
                fence_length = 0
            continue
        if fence_character is None:
            visible.append(INLINE_CODE.sub("", line))
    return "\n".join(visible)


def citation_keys(text: str) -> tuple[str, ...]:
    """Return rendered Pandoc citation keys, excluding Quarto cross-references."""
    visible = _without_nonrendered_markdown(text)
    return tuple(
        match.group("key")
        for match in CITATION.finditer(visible)
        if not match.group("key").startswith(CROSS_REFERENCE_PREFIXES)
    )


def _render_view(label: str, entries: tuple[BibEntry, ...]) -> str:
    header = (
        "% Generated by scripts/build_ijds_bibliography_views.py.\n"
        "% Source of truth: paper/references.bib; do not edit this view directly.\n"
        f"% View: {label}; entry count: {len(entries)}.\n"
    )
    if not entries:
        return header
    return header + "\n" + "\n\n".join(entry.text for entry in entries) + "\n"


def _relative(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def build_bibliography_views(*, root: Path = ROOT, check: bool = False) -> bool:
    """Build or check the complete, disjoint active/reserve bibliography partition."""
    master = root / MASTER_RELATIVE
    sources = tuple(root / relative for relative in SOURCE_RELATIVES)
    active_output = root / ACTIVE_RELATIVE
    reserve_output = root / RESERVE_RELATIVE
    partition_output = root / PARTITION_RELATIVE

    master_bytes_before = master.read_bytes()
    entries = parse_bibtex_entries(master_bytes_before.decode("utf-8"))
    master_keys = tuple(entry.key for entry in entries)
    master_key_set = set(master_keys)

    citation_sources: list[dict[str, object]] = []
    cited: set[str] = set()
    for source in sources:
        source_bytes = source.read_bytes()
        occurrences = citation_keys(source_bytes.decode("utf-8"))
        unique = tuple(sorted(set(occurrences)))
        citation_projection = ("\n".join(unique) + "\n").encode("utf-8")
        cited.update(unique)
        citation_sources.append(
            {
                "path": _relative(source, root),
                "citation_key_sha256": _sha256(citation_projection),
                "citation_key_count": len(unique),
                "citation_keys": list(unique),
            }
        )

    missing = tuple(sorted(cited.difference(master_key_set)))
    if missing:
        raise RuntimeError(f"Citations missing from the master bibliography: {list(missing)!r}.")

    active_entries = tuple(entry for entry in entries if entry.key in cited)
    reserve_entries = tuple(entry for entry in entries if entry.key not in cited)
    active_keys = tuple(entry.key for entry in active_entries)
    reserve_keys = tuple(entry.key for entry in reserve_entries)
    active_set = set(active_keys)
    reserve_set = set(reserve_keys)
    if active_set != cited:
        raise RuntimeError("Active bibliography keys do not equal the body/supplement citations.")
    if active_set & reserve_set:
        raise RuntimeError("Active and reserve bibliography views overlap.")
    if active_set | reserve_set != master_key_set:
        raise RuntimeError("Active and reserve bibliography views do not partition the master.")

    active_text = _render_view("active citations in body plus supplement", active_entries)
    reserve_text = _render_view("uncited reserve", reserve_entries)
    partition = {
        "schema_version": "1.0",
        "generated_by": "scripts/build_ijds_bibliography_views.py",
        "master_bibliography": {
            "path": _relative(master, root),
            "sha256": _sha256(master_bytes_before),
            "entry_count": len(entries),
            "keys": list(master_keys),
        },
        "citation_sources": citation_sources,
        "views": {
            "active": {
                "path": _relative(active_output, root),
                "sha256": _sha256(active_text.encode("utf-8")),
                "entry_count": len(active_entries),
                "keys": list(active_keys),
            },
            "reserve": {
                "path": _relative(reserve_output, root),
                "sha256": _sha256(reserve_text.encode("utf-8")),
                "entry_count": len(reserve_entries),
                "keys": list(reserve_keys),
            },
        },
        "validation": {
            "active_equals_body_plus_supplement_citations": active_set == cited,
            "partition_complete": active_set | reserve_set == master_key_set,
            "partition_disjoint": not active_set & reserve_set,
            "duplicate_master_keys": [],
            "missing_citation_keys": list(missing),
        },
    }
    partition_text = json.dumps(partition, indent=2, ensure_ascii=False, sort_keys=True) + "\n"

    master_bytes_after = master.read_bytes()
    if master_bytes_after != master_bytes_before:
        raise RuntimeError("The master bibliography changed while its views were being built.")

    outputs = {
        active_output: active_text,
        reserve_output: reserve_text,
        partition_output: partition_text,
    }
    if check:
        return all(
            path.is_file() and path.read_bytes() == expected.encode("utf-8")
            for path, expected in outputs.items()
        )

    for path, content in outputs.items():
        atomic_write_text(path, content)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when any generated bibliography view or receipt is stale",
    )
    args = parser.parse_args()
    current = build_bibliography_views(check=args.check)
    if args.check and not current:
        print("stale generated bibliography views")
        return 1
    verb = "are current" if args.check else "were generated"
    print(f"IJDS bibliography views {verb}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
